### ISSUE TITLE
Wrong background / dark mode implementation?

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#146] opened 2020-09-15 13:55 UTC
On [topic 6 unit 3 step 1](http://tmp.kiwix.org:9991/phzh_core-greek-one_el_2020-08/A/course/core-ellenika-01/thema-6o-zo-me-ugieino-tropo/enoteta-3e-oi-kindunoi-ton-narkotikon-kai-tou-alkool/bema-1/index.html) there is a hard to read dark background, whereas the original is white background.

![Topic 7 Unit 3 step 2 (too dark background)](https://user-images.githubusercontent.com/21675885/93219555-c6f92700-f76b-11ea-9c10-9ea9e40b7ba7.jpg)

**Comment by rgaudin** [comment] 2020-09-15 13:59
Duplicate of #140

**Comment by satyamtg** [comment] 2020-09-15 13:59
This dark background error has already been fixed with #143. Though we haven't built a new ZIM for the greek version.

**Closed by rgaudin** 2020-09-15 13:59 UTC
Labels: bug
